name: SignShop
main: org.wargamer2010.signshop.SignShop
version: 1.8.1
author: Wargamer2010
softdepend: [Vault, Multiverse-Core]
commands:
  signshop:
    description: Admin commands for SignShop
    usage: /signshop [reload]