name: SignShop
main: org.wargamer2010.signshop.SignShop
version: 2.5.4Dev
dev-url: http://dev.bukkit.org/server-mods/signshop
author: Wargamer2010 and Devinish
softdepend: [Vault, Multiverse-Core, ShowCaseStandalone, Deadbolt, Notifications]
commands:
  signshop:
    description: Admin commands for SignShop
    usage: /signshop [reload|stats|version|help]