name: SignShop
main: org.wargamer2010.signshop.SignShop
version: 2.2.5
author: Wargamer2010
softdepend: [Vault, Multiverse-Core, ShowCaseStandalone, Deadbolt]
commands:
  signshop:
    description: Admin commands for SignShop
    usage: /signshop [reload]