name: "SignShop"
main: org.wargamer2010.signshop.SignShop
api-version: "1.13"
version: "${project.version}"
dev-url: http://dev.bukkit.org/server-mods/signshop
authors: [Wargamer2010, Devinish, Weaves]
softdepend: [Vault, Towny, GriefPrevention, WorldGuard, CMI]
commands:
  signshop:
    description: Admin commands for SignShop
    usage: /signshop [reload|stats|version|about|help|sign|tutorial]
